CREATE DATABASE IF NOT EXISTS kantinku;
USE kantinku;
-- 1. TABEL PENGGUNA (users)
CREATE TABLE IF NOT EXISTS users (
id INT AUTO_INCREMENT PRIMARY KEY,
nama VARCHAR(100) NOT NULL,
username VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
role ENUM('admin', 'petugas', 'siswa') NOT NULL DEFAULT 'siswa',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
-- 2. TABEL KATEGORI (kategori)
CREATE TABLE IF NOT EXISTS kategori (
id INT AUTO_INCREMENT PRIMARY KEY,
nama_kategori VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB;
-- 3. TABEL PRODUK (produk)
CREATE TABLE IF NOT EXISTS produk (
id INT AUTO_INCREMENT PRIMARY KEY,
kategori_id INT NOT NULL,
nama_produk VARCHAR(100) NOT NULL,
harga INT NOT NULL,
stok INT NOT NULL DEFAULT 0,
foto VARCHAR(255) DEFAULT 'default.jpg',
FOREIGN KEY (kategori_id) REFERENCES kategori(id) ON DELETE CASCADE
) ENGINE=InnoDB;
-- 4. TABEL PESANAN HEADER (pesanan)
CREATE TABLE IF NOT EXISTS pesanan (
id INT AUTO_INCREMENT PRIMARY KEY,
kode_pesanan VARCHAR(50) NOT NULL UNIQUE,
user_id INT NOT NULL,
total_harga INT NOT NULL,
status ENUM('menunggu', 'diproses', 'selesai', 'batal') NOT NULL DEFAULT 'menunggu',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
-- 5. TABEL DETAIL PESANAN ITEM (detail_pesanan)
CREATE TABLE IF NOT EXISTS detail_pesanan (
id INT AUTO_INCREMENT PRIMARY KEY,
pesanan_id INT NOT NULL,
produk_id INT NOT NULL,
jumlah INT NOT NULL,
subtotal INT NOT NULL,
FOREIGN KEY (pesanan_id) REFERENCES pesanan(id) ON DELETE CASCADE,
FOREIGN KEY (produk_id) REFERENCES produk(id) ON DELETE CASCADE
) ENGINE=InnoDB;
